/*******************************************************************************
 * Copyright (c) 2014 Pivotal Software, Inc. 
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, 
 * Version 2.0 (the "License�); you may not use this file except in compliance 
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 *  Contributors:
 *     Pivotal Software, Inc. - initial API and implementation
 ********************************************************************************/
package org.cloudfoundry.ide.eclipse.server.core.internal.log;

import org.cloudfoundry.client.lib.CloudFoundryOperations;
import org.cloudfoundry.client.lib.RestLogEntry;

/**
 * Streams the trace log generated by the Cloud Foundry trace framework. For
 * example, a UI component may implement this interface and trace the log to a
 * console when the Cloud Foundry trace framework notifies it that there is a
 * new trace log. Alternately, another component can implement this interface
 * and trace to a log file.
 *
 */
public interface ICloudTracer {

	/**
	 * Trace a new log entry generated by the Cloud Foundry framework.
	 * Typically, this gets invoked by the framework when a new REST request is
	 * being processed in the {@link CloudFoundryOperations}.
	 * @param restLogEntry
	 */
	public void traceNewLogEntry(RestLogEntry restLogEntry);

}
